curl -X 'POST' \
  'http://localhost:8081/api/Forecasts?weathermanId=erear' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "forecastDateTime": "2023-01-27T18:16:00.615Z",
  "celsius": 59.1
}'