version: '3.4'

services:
  app:
    image: companywebcast
    container_name: app
    build:
      context: .
      dockerfile: ./Euronext.CompanyWebcast.API/Dockerfile
    ports:
    - "8081:80"
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    environment:
      SA_PASSWORD: "Password@12345"
      ACCEPT_EULA: "Y"
    ports:
    - "14331:1433"